name: Create

on:
  push:
  schedule:
    - cron: '13 12 * * *'

jobs:
  create:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        APP_TYPE: ['api', 'static', 'full']

    env:
      APP_TYPE_CI: ${{ matrix.APP_TYPE }}
      GITHUB_TOKEN: ${{ secrets.SPECIAL_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Create the app
        run: bash create.sh

      - name: Upload the app
        run: bash upload.sh
