name: Create

on:
  push:
  schedule:
    - cron: '13 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        APP_TYPE: ['api', 'static', 'full']

    env:
      LENGTH_CI: ${{ matrix.LENGTH }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Create the app
        run: bash create.sh
