name: Create and Push

on:
  push:
  schedule:
    - cron: '13 12 * * *'

jobs:
  create:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        APP_TYPE: ['api', 'static', 'full']

    env:
      APP_TYPE_CI: ${{ matrix.APP_TYPE }}
      GITHUB_TOKEN: ${{ secrets.SPECIAL_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Create the app
        run: bin/create

      - name: Create the app in GitHub
        run: source bin/definitions && bin/create-github "$ORG_NAME" "$REPO_NAME" 'App created by GitHub Workflows for rubyonracetracks/repo-manager'

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: bin/config-ssh 'ed25519'

      - name: Git Push
        run: bin/push
