name: Delete Test Apps

on:
  schedule:
    - cron: '01 12 * * *'

jobs:
  delete:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        APP_TYPE: ['api', 'static', 'full']

    env:
      APP_TYPE_CI: ${{ matrix.APP_TYPE }}
      GITHUB_TOKEN: ${{ secrets.SPECIAL_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Provisioning
        run: bin/provision

      - name: Delete test apps
        run: bin/delete-test-apps
